### ISSUE TITLE
Convert excel to to HTML does not export the images to the HTML

### ISSUE THREAD

**Issue by timothykasaga** [GemBoxLtd/GemBox.Spreadsheet.Examples#1]
Hi team, I have used the sample code for converting an excel file to PDF but the images are not moved to HTML

```csharp
// Set license key to use GemBox.Spreadsheet in Free mode.
SpreadsheetInfo.SetLicense("FREE-LIMITED-KEY");

var workbook = ExcelFile.Load(@"D:\Work\DotNet\TestViewer\DocumentViewer\storage\test.xls");
var worksheet = workbook.Worksheets[0];

// Some of the properties from ExcelPrintOptions class are supported in HTML export.
worksheet.PrintOptions.PrintHeadings = true;
worksheet.PrintOptions.PrintGridlines = true;

// Print area can be used to specify custom cell range which should be exported to HTML.
worksheet.NamedRanges.SetPrintArea(worksheet.Cells.GetSubrange("A1", "M42"));

var options = new HtmlSaveOptions()
{
    HtmlType = HtmlType.Html,
    SelectionType = SelectionType.EntireFile,
    EmbedImages = true,
};

workbook.Save(@"D:\Work\DotNet\TestViewer\DocumentViewer\storage\HtmlExport.html", options);
```

**Comment by timothykasaga** [comment]
I have noted it's only working for .xlsx if use a .xls the images are rendered, is this the intented design

**Comment by mario-gembox** [comment]
Hi,

I'm really sorry for the late reply.
Unfortunately, I have just now realized that monitoring, watching, was disabled after we moved repositories from GitHub account to GitHub organization.

Nevertheless, the reason why this problem occurs is that GemBox.Spreadsheet currently doesn't support images in XLS file format, they are supported in XLSX, ODS, HTML, PDF, XPS and image file formats.
Please refer to [Supported File Formats](https://www.gemboxsoftware.com/spreadsheet/help/html/Supported_File_Formats.htm) help page, it contains a table of supported features for each file format.

However, I would like to point out that we are currently working on this, [Preserving Images when Loading XLS Files](https://support.gemboxsoftware.com/feedback/view/preserving-images-when-loading-xls-files).
We plan to release improved XLS reader and writer with more supported features, it should be available within a month.

Regards,

Mario
GemBox d.o.o.

**Comment by mario-gembox** [comment]
Hi,

The current latest version of GemBox.Spreadsheet supports pictures in older XLS format, see [Supported File Formats](https://www.gemboxsoftware.com/spreadsheet/help/html/Supported_File_Formats.htm) help page.

You can download it from [BugFixes](https://www.gemboxsoftware.com/spreadsheet/downloads/BugFixes.htm) or from [NuGet](https://www.nuget.org/packages/GemBox.Spreadsheet/).

Regards,

Mario
GemBox d.o.o.
