### ISSUE TITLE
[C# /Platforms/MAUI] Cannot get a matching glyph typeface for font 'Calibri'

### ISSUE THREAD

**Issue by dovhoang** [GemBoxLtd/GemBox.Spreadsheet.Examples#3]
I am using `GemBox.Spreadsheet` for Xamarin.Android project for converting Excel to Pdf file

Run MAUI demo in android device got below issue: 

![Screenshot_1687424613](https://github.com/GemBoxLtd/GemBox.Spreadsheet.Examples/assets/55356231/cdf0cb17-0581-446b-93c6-3c51aee9d119)

I try creating my demo Xamarin.Android project and get the same issue
![Screenshot 2023-06-22 at 14 02 02](https://github.com/GemBoxLtd/GemBox.Spreadsheet.Examples/assets/55356231/8319143f-5a10-4105-b625-d36be0de6acf)

Detect location of exception, I found function `FontToWin32Font` that may not available for android env
![Screenshot 2023-06-22 at 16 10 12](https://github.com/GemBoxLtd/GemBox.Spreadsheet.Examples/assets/55356231/4448479b-e60e-4106-97f6-ce42694f74ca)

Thank for your reading!

**Comment by mario-gembox** [comment]
Hi,
you need to add the font files to your project.
Please try embedding the "Calibri" font files as described in the [`FontSettings.FontsBaseResourceLocation`](https://www.gemboxsoftware.com/spreadsheet/docs/GemBox.Spreadsheet.FontSettings.html#GemBox_Spreadsheet_FontSettings_FontsBaseResourceLocation) property remarks.
Regards,
Mario

**Comment by dovhoang** [comment]
> Hi, you need to add the font files to your project. Please try embedding the "Calibri" font files as described in the [`FontSettings.FontsBaseResourceLocation`](https://www.gemboxsoftware.com/spreadsheet/docs/GemBox.Spreadsheet.FontSettings.html#GemBox_Spreadsheet_FontSettings_FontsBaseResourceLocation) property remarks. Regards, Mario

Still throw an exception, may I embed the font wrong?
Thanks!

```
android.runtime.JavaProxyThrowable: System.InvalidOperationException: Cannot get a matching glyph typeface for font 'Times New Roman'.
at GemBox.Drawing.Win32Font..ctor (System.String familyName, GemBox.Drawing.Win32FontStyle style, System.Double emSize, GemBox.Drawing.Legacy.TypefaceCache typefaceCache)
```

![Screenshot 2023-06-22 at 17 19 18](https://github.com/GemBoxLtd/GemBox.Spreadsheet.Examples/assets/55356231/e63ced77-1bb7-45d0-8338-7d6c10cb2071)

**Comment by dovhoang** [comment]
I installed this font on the device; it worked, so I am closing this issue.
